# Site
name: 'JINHYEOK KANG'
description: 'Test with MAC'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: 'https://pokachip.github.io'
disqus: 'demowebsite'
email: 'wowthemesnet@gmail.com'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
   KANG:
      name:           JINHYEOK KANG
      site:           https://pokachip.github.io
      avatar:         /assets/images/jinhyeok.jpeg
      bio:            "Wi-Fi, Bluetooth hardware engineer<br>FW 등 software 공부 중"
      location:       경기도 성남시
      email:          mochapott@icloud.com
      links:
        - label: "Instagram"
          icon : "fab fa-fw fa-2402mhz"
          url  : "https://instagram.com/2402mhz?igshid=NTc4MTIwNjQ2YQ=="

 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: KANG
      avatar: /assets/images/jinhyeok.jpeg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]

sass:
   sass_dir: bower_components/bootstrap/scss

# Exclude from processing.
exclude:
  - bower_components

future: true